language: ruby

rvm:
  - jruby-18mode
  - jruby-19mode
  - jruby-head

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6

# http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 

script:
  - build/run bootstrap
  - build/run backend:test
  - build/run backend:integration
# - build/run common:test  # https://github.com/hudmol/archivesspace/commit/193fe9a3990da74e37e98140c9eaa264ec801643#L0R106
  - build/run dist
  - build/run selenium:test
