# TODO: Testing with multiple database backends. By default,
# ArchivesSpace will run these tests against the embedded Derby database
# (see config/config-distribution.rb). To investigate this see 
# http://about.travis-ci.org/docs/user/database-setup/

language: ruby

rvm:
  # The bootstrap script installs jruby, so this setting does not matter.
  - jruby-19mode

before_script:
  - mysql -e 'create database archivesspace default character set utf8;'

jdk:
  - oraclejdk7

branches:
  only:
    - travis-mysql

#     exec("java", "-Xmx2g", "-XX:MaxPermSize=512M",
#             "-Daspace-test-suite=true",
#             "-Daspace.config.db_url=" . $db_url,
#             "-Dfile.encoding=UTF-8",
#             "-Daspace.config.data_directory=$test_dir",
#             "-Daspace.config.backend_url=http://localhost:${backend_port}",
#             "-Daspace.config.frontend_url=http://localhost:${frontend_port}",
#             "-jar", "$base/archivesspace.jar", $frontend_port, $backend_port);

script:
  - build/run bootstrap
  - build/run dist
  # crank up the mysql server in the background
  # set up to run test on mysql
  - JAVA_OPTS="-Daspace.config.solr_url=http://localhost:5000/ -Daspace.config.frontend_url=http://localhost:3000 -Daspace.config.backend_url=http://localhost:4000" java -Xmx2g -XX:MaxPermSize=512M -Dfile.encoding=UTF-8 -Daspace.config.search_user_secret=devserver -Daspace.config.public_user_secret=devserver -Daspace.config.db_url="jdbc:mysql:localhost:3306/archivesspace?user=root&password=&useUnicode=true&characterEncoding=UTF-8" -jar archivesspace.jar 3000 4000 5000 > /dev/null 2>&1 & 
  # https://gist.github.com/tingletech/2e62e088126913a36cdc#file-migrate-pl-L103
  # run the tests once on the embedded db
  - build/run backend:test
  - build/run backend:integration
  - build/run common:test
  - curl -v -X POST http://localhost:4000/setup/update_schema
  - xvfb-run --server-args="-screen 0 1024x768x24" ./build/run selenium:test
  - xvfb-run --server-args="-screen 0 1024x768x24" ./build/run selenium:public:test 
  # run the tests a second time on the mysql db
  - export ASPACE_FRONTEND_URL=http://localhost:3000
  - export ASPACE_BACKEND_URL=http://localhost:4000 
  - export JAVA_OPTS="-Daspace.config.solr_url=http://localhost:5000/"
  - build/run backend:test
  - build/run backend:integration
  - xvfb-run --server-args="-screen 0 1024x768x24" ./build/run selenium:test
  - xvfb-run --server-args="-screen 0 1024x768x24" ./build/run selenium:public:test 

notifications:
  irc: "irc.freenode.org#archivesspace"
  # don't send email for now, until we know who we want to receive it
  email: false
