language: ruby

rvm:
  - jruby-18mode
  - jruby-19mode
#  - jruby-head

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6

script:
  - build/run bootstrap
  - build/run backend:test
  - build/run backend:integration
  - build/run dist
