# TODO: Testing with multiple database backends. By default,
# ArchivesSpace will run these tests against the embedded Derby database
# (see config/config-distribution.rb). To investigate this see 
# http://about.travis-ci.org/docs/user/database-setup/

env:
  global:
    - secure: "GgeeGL/kurKF75a/xiDRtNvt+GzSPZasQdCXUXZjEvrzhJdn/1yekVajzOS1\n5d9Y5QizMQbMjL1qjlgzArn44D7qPiycRP5fh1zYUl2IJZRkbgIai3wLPLZ6\nc9gKd5STwiD8TgRht6T83FOOyG4nYPTcB2FQmCluDIzXs5tSCO8="
    - HOSTNAME=`hostname`

language: ruby

rvm:
  # The bootstrap script installs jruby, so this setting does not matter.
  - jruby-19mode

jdk:
  - oraclejdk7

branches:
  only:
    - master
    - saucelabs-travis

script:
  - hostname
  - build/run bootstrap
  - build/run backend:test
  - build/run backend:integration
  - build/run common:test
  - build/run dist
  - build/run selenium:test

notifications:
  irc: "irc.freenode.org#archivesspace"
  # don't send email for now, until we know who we want to receive it
  email: false
