# TODO: Testing with multiple database backends. By default,
# ArchivesSpace will run these tests against the embedded Derby database
# (see config/config-distribution.rb). To investigate this see 
# http://about.travis-ci.org/docs/user/database-setup/

language: ruby

rvm:
  # The bootstrap script installs jruby, so this setting does not matter.
  - jruby-19mode

jdk:
  - openjdk6

script:
  - build/run bootstrap
  - build/run backend:test
  - build/run backend:integration
  - build/run common:test
  - build/run dist
  - xvfb-run --server-args="-screen 0 1024x768x24" ./build/run selenium:test

notifications:
  irc: "irc.freenode.org#archivesspace"
  # don't send email for now, until we know who we want to receive it
  email: false
