# TODO: Testing with multiple database backends. By default,
# ArchivesSpace will run these tests against the embedded Derby database
# (see config/config-distribution.rb). To investigate this see 
# http://about.travis-ci.org/docs/user/database-setup/

env:
  global:
    # http://saucelabs.com/opensource/travis
    # http://about.travis-ci.org/docs/user/build-configuration/#Secure-environment-variables
    - secure: "cQFuCxnO81j/oDv4v8LiOd3NueQijDctjBjqwidM5eMP30c6s+gxummhTQxw\nP707qBNRrleOznI17MF90aeZ4LsKJN9glcYYmKmOwqBbum5u+SduKNb2SYAX\n1lPc6FabymJT5mqMD1+UNp5XFdQP68M+1pN/aP3e8o1t3BASRsE="
    - secure: "Kx/SGvnx6kE4PtsvPa5y9YT2OhCjpdKxa+0nCjU2dsK+l177eSeQTttjbwE1\nLswz1n+7bs0n9l8GCfq6QAAH7KMpKQUDWultQ4RlTghLX5IubqsMy8QN3YrI\nc67pcB2pYAZFXrgesNz3xRohkfdjjmK/Rx+/NIwgTdJjZQG2i2s="

language: ruby

rvm:
  # The bootstrap script installs jruby, so this setting does not matter.
  - jruby-19mode

jdk:
  - oraclejdk7

branches:
  only:
    - master
    - saucelabs-travis

before_install:
  - wget "http://saucelabs.com/downloads/Sauce-Connect-latest.zip"
  - unzip Sauce-Connect-latest.zip
  - java -jar Sauce-Connect.jar $SAUCE_USERNAME $SAUCE_ACCESS_KEY &

script:
  - build/run bootstrap
  - build/run backend:test
  - build/run backend:integration
  - build/run common:test
  - build/run dist
  - java -XX:MaxPermSize=256m -Xmx256m -Dfile.encoding=UTF-8 -jar archivesspace.jar 3636 4545 &
  - sleep 120
  - export ASPACE_FRONTEND_URL=http://localhost:3636
  - export ASPACE_BACKEND_URL=http://localhost:4545
  - export TEST_NAME='Repositories';	 			build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='Groups';	 				build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='Subjects';	 			build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='Agents';	 				build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='Accessions';	 			build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='Collection Management Records'; 		build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='Events';	 				build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='Resources and archival object trees'; 	build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='Notes';	 				build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='Digital Objects';	 			build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='User management';	 			build/run selenium:test -Dexample="$TEST_NAME"
  - export TEST_NAME='Users and authentication'; 		build/run selenium:test -Dexample="$TEST_NAME"

notifications:
  irc: "irc.freenode.org#archivesspace"
  # don't send email for now, until we know who we want to receive it
  email: false
